# Server Configuration
server.port=8081
spring.application.name=animal-detection-api

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Upload Directory
app.upload.dir=../uploads
app.python.script.dir=../

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200,http://localhost:8000,file://,null

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/animal_detection_app
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.esprit.animaldetection=DEBUG
logging.level.org.hibernate.SQL=DEBUG
